config/routes.rb
Rails.application.routes.draw do
  get 'cookies', to: 'cookies#index'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cookies_controller.rb
class CookiesController < ApplicationController
  def index
    session[:cookies_accepted] = params[:cookies_accepted] if params[:cookies_accepted]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    session[:cookies_accepted] = nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cookies/index.html.erb
<%= turbo_frame_tag :cookies_modal do %>
  <% if session[:cookies_accepted].nil? %>
    <section class="cookies-modal">
      <h1>Cookies policy</h1>
      <p>We use cookies to provide a better browsing experience</p>
      <%= link_to "✅ Accept", cookies_path(cookies_accepted: true) %>
      <%= link_to "⛔ Reject", cookies_path(cookies_accepted: false) %>
    </section>
  <% end %>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookieapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%#= render 'layout/google_analytcis' if session[:cookies_accepted] == true %>
  </head>

  <body>
    <%= session[:cookies_accepted] %>
    <%= yield %>
    <%= turbo_frame_tag :cookies_modal, src: cookies_path if session[:cookies_accepted].nil? %>
  </body>
</html>